version: '3.8'

networks:
  inception:
    name: inception

volumes:
  data_www:
    name: www
    driver_opts:
      type: 'none'
      device: '${HOME}/data/www'
      o: 'bind'
  data_db:
    name: db
    driver_opts:
      type: 'none'
      device: '${HOME}/data/db'
      o: 'bind'

services:
  nginx:
    container_name: nginx
    image: nginx:inc
    build: ./requirements/nginx
    volumes:
      - data_www:/var/www/inception
    networks:
      - inception
    ports:
      - 443:443
    depends_on:
      - wordpress
      - adminer
      - rps
    environment:
      - CERT=$CERT
      - CERT_KEY=$CERT_KEY
      - DOMAIN_NAME=$DOMAIN_NAME
    restart: always
  mariadb:
    container_name: mariadb
    image: mariadb:inc
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - data_db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
    restart: always
  wordpress:
    container_name: wordpress
    image: wordpress:inc
    build: ./requirements/wordpress
    volumes:
      - data_www:/var/www/inception
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    restart: always
  redis:
    container_name: redis
    image: redis:inc
    build: ./requirements/bonus/redis
    networks:
      - inception
    restart: always
  adminer:
    container_name: adminer
    image: adminer:inc
    build: ./requirements/bonus/adminer
    networks:
      - inception
    ports:
      - 8080:8080
    restart: always
  rps:
    container_name: rps
    image: rps:inc
    build: ./requirements/bonus/rps
    networks:
      - inception
    ports:
      - 5000:5000
    restart: always
  prometheus:
    container_name: prometheus
    image: prometheus:inc
    build: ./requirements/bonus/prometheus
    networks:
      - inception
    ports:
      - 9090:9090
    environment:
      - HOST=$HOST
    restart: always
  grafana:
    image: grafana:inc
    container_name: grafana
    build: ./requirements/bonus/grafana
    networks:
      - inception
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    restart: always
