version: '3.8'

networks:
  inception:

volumes:
  data_www:
    name: www
    driver_opts:
      type: 'none'
      device: '${PWD}/www'
      o: 'bind'
  data_db:
    name: db
    driver_opts:
      type: 'none'
      device: '${PWD}/db'
      o: 'bind'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    volumes:
      - data_www:/var/www/inception
    networks:
      - inception
    ports:
      - 443:443
    depends_on:
      - wordpress
    environment:
      - CERT=$CERT
      - CERT_KEY=$CERT_KEY
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - data_db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - data_www:/var/www/inception
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env