version: '3.8'

networks:
  inception:
    name: inception

volumes:
  data_www:
    name: www
    driver_opts:
      type: 'none'
      device: '${PWD}/www'
      o: 'bind'
  data_db:
    name: db
    driver_opts:
      type: 'none'
      device: '${PWD}/db'
      o: 'bind'
  data_rps:
    name: rps
    driver_opts:
      type: 'none'
      device: '${PWD}/rps'
      o: 'bind'
  provisioning:
    name: provisioning
    driver_opts:
      type: 'none'
      device: '${PWD}/grafana'
      o: bind

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    volumes:
      - data_www:/var/www/inception
      - data_rps:/var/www/rps
    networks:
      - inception
    ports:
      - 443:443
    depends_on:
      - wordpress
      - adminer
    environment:
      - CERT=$CERT
      - CERT_KEY=$CERT_KEY
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - data_db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - data_www:/var/www/inception
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy        
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis
    build: ./requirements/redis
    networks:
      - inception
  adminer:
    container_name: adminer
    image: adminer
    build: ./requirements/adminer
    networks:
      - inception
    ports:
      - 8080
  rps:
    container_name: rps
    image: rps
    build: ./requirements/rps
    networks:
      - inception
    volumes:
      - data_rps:/var/www/rps
  prometheus:
    container_name: prometheus
    image: prometheus
    build: ./requirements/prometheus
    networks:
      - inception
    ports:
      - 9090
  grafana:
    image: grafana
    container_name: grafana
    build: ./requirements/grafana
    networks:
      - inception
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - provisioning:/etc/grafana/